import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 
  | 'en' | 'es' | 'fr' | 'de' | 'pt' | 'ru' | 'ja' | 'ko' | 'zh' | 'ar' | 'it' | 'nl' | 'tr' | 'pl' | 'vi' | 'th' | 'id' | 'ms'
  | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' | 'as' | 'ur';

interface LanguageOption {
  code: Language;
  label: string;
  flag: string;
  region?: string;
}

export const languages: LanguageOption[] = [
  // Major World Languages
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', label: 'Português', flag: '🇧🇷' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
  { code: 'nl', label: 'Nederlands', flag: '🇳🇱' },
  { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { code: 'pl', label: 'Polski', flag: '🇵🇱' },
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', label: 'ไทย', flag: '🇹🇭' },
  { code: 'id', label: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', label: 'Bahasa Melayu', flag: '🇲🇾' },
  // Indian Languages
  { code: 'hi', label: 'हिंदी', flag: '🇮🇳', region: 'India' },
  { code: 'bn', label: 'বাংলা', flag: '🇮🇳', region: 'India' },
  { code: 'te', label: 'తెలుగు', flag: '🇮🇳', region: 'India' },
  { code: 'mr', label: 'मराठी', flag: '🇮🇳', region: 'India' },
  { code: 'ta', label: 'தமிழ்', flag: '🇮🇳', region: 'India' },
  { code: 'gu', label: 'ગુજરાતી', flag: '🇮🇳', region: 'India' },
  { code: 'kn', label: 'ಕನ್ನಡ', flag: '🇮🇳', region: 'India' },
  { code: 'ml', label: 'മലയാളം', flag: '🇮🇳', region: 'India' },
  { code: 'or', label: 'ଓଡ଼ିଆ', flag: '🇮🇳', region: 'India' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', flag: '🇮🇳', region: 'India' },
  { code: 'as', label: 'অসমীয়া', flag: '🇮🇳', region: 'India' },
  { code: 'ur', label: 'اردو', flag: '🇮🇳', region: 'India' },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    title: 'Internet Speed Test',
    subtitle: 'Browser-based network performance analysis',
    startTest: 'Start Test',
    stop: 'Stop',
    restartTest: 'Restart Test',
    copyResults: 'Copy Results',
    copied: 'Copied',
    advertisement: 'Advertisement',
    download: 'Download',
    upload: 'Upload',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Speed Over Time',
    testingDownload: 'Testing Download',
    testingUpload: 'Testing Upload',
    testComplete: 'Test Complete',
    readyToTest: 'Ready to Test',
    testDuration: 'Test Duration',
    footer: 'Browser-based estimation. Results may vary from ISP measurements.',
  },
  es: {
    title: 'Test de Velocidad',
    subtitle: 'Análisis de rendimiento de red',
    startTest: 'Iniciar',
    stop: 'Detener',
    restartTest: 'Reiniciar',
    copyResults: 'Copiar',
    copied: 'Copiado',
    advertisement: 'Publicidad',
    download: 'Descarga',
    upload: 'Subida',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Velocidad',
    testingDownload: 'Descarga',
    testingUpload: 'Subida',
    testComplete: 'Completo',
    readyToTest: 'Listo',
    testDuration: 'Duración',
    footer: 'Estimación del navegador.',
  },
  fr: {
    title: 'Test de Vitesse',
    subtitle: 'Analyse des performances réseau',
    startTest: 'Démarrer',
    stop: 'Arrêter',
    restartTest: 'Redémarrer',
    copyResults: 'Copier',
    copied: 'Copié',
    advertisement: 'Publicité',
    download: 'Téléchargement',
    upload: 'Envoi',
    ping: 'Ping',
    jitter: 'Gigue',
    speedOverTime: 'Vitesse',
    testingDownload: 'Téléchargement',
    testingUpload: 'Envoi',
    testComplete: 'Terminé',
    readyToTest: 'Prêt',
    testDuration: 'Durée',
    footer: 'Estimation du navigateur.',
  },
  de: {
    title: 'Geschwindigkeitstest',
    subtitle: 'Netzwerkleistungsanalyse',
    startTest: 'Starten',
    stop: 'Stoppen',
    restartTest: 'Neustart',
    copyResults: 'Kopieren',
    copied: 'Kopiert',
    advertisement: 'Werbung',
    download: 'Download',
    upload: 'Upload',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Geschwindigkeit',
    testingDownload: 'Download',
    testingUpload: 'Upload',
    testComplete: 'Fertig',
    readyToTest: 'Bereit',
    testDuration: 'Dauer',
    footer: 'Browser-Schätzung.',
  },
  pt: {
    title: 'Teste de Velocidade',
    subtitle: 'Análise de desempenho de rede',
    startTest: 'Iniciar',
    stop: 'Parar',
    restartTest: 'Reiniciar',
    copyResults: 'Copiar',
    copied: 'Copiado',
    advertisement: 'Publicidade',
    download: 'Download',
    upload: 'Upload',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Velocidade',
    testingDownload: 'Download',
    testingUpload: 'Upload',
    testComplete: 'Completo',
    readyToTest: 'Pronto',
    testDuration: 'Duração',
    footer: 'Estimativa do navegador.',
  },
  ru: {
    title: 'Тест скорости',
    subtitle: 'Анализ производительности сети',
    startTest: 'Начать',
    stop: 'Стоп',
    restartTest: 'Повторить',
    copyResults: 'Копировать',
    copied: 'Скопировано',
    advertisement: 'Реклама',
    download: 'Загрузка',
    upload: 'Выгрузка',
    ping: 'Пинг',
    jitter: 'Джиттер',
    speedOverTime: 'Скорость',
    testingDownload: 'Загрузка',
    testingUpload: 'Выгрузка',
    testComplete: 'Готово',
    readyToTest: 'Готов',
    testDuration: 'Время',
    footer: 'Оценка браузера.',
  },
  ja: {
    title: 'スピードテスト',
    subtitle: 'ネットワーク性能分析',
    startTest: '開始',
    stop: '停止',
    restartTest: '再テスト',
    copyResults: 'コピー',
    copied: 'コピー済',
    advertisement: '広告',
    download: 'ダウンロード',
    upload: 'アップロード',
    ping: 'Ping',
    jitter: 'ジッター',
    speedOverTime: '速度',
    testingDownload: 'ダウンロード中',
    testingUpload: 'アップロード中',
    testComplete: '完了',
    readyToTest: '準備完了',
    testDuration: '時間',
    footer: 'ブラウザ推定値。',
  },
  ko: {
    title: '속도 테스트',
    subtitle: '네트워크 성능 분석',
    startTest: '시작',
    stop: '중지',
    restartTest: '다시',
    copyResults: '복사',
    copied: '복사됨',
    advertisement: '광고',
    download: '다운로드',
    upload: '업로드',
    ping: '핑',
    jitter: '지터',
    speedOverTime: '속도',
    testingDownload: '다운로드',
    testingUpload: '업로드',
    testComplete: '완료',
    readyToTest: '준비',
    testDuration: '시간',
    footer: '브라우저 추정치.',
  },
  zh: {
    title: '网速测试',
    subtitle: '网络性能分析',
    startTest: '开始测试',
    stop: '停止',
    restartTest: '重新测试',
    copyResults: '复制',
    copied: '已复制',
    advertisement: '广告',
    download: '下载',
    upload: '上传',
    ping: '延迟',
    jitter: '抖动',
    speedOverTime: '速度趋势',
    testingDownload: '下载测试',
    testingUpload: '上传测试',
    testComplete: '完成',
    readyToTest: '准备',
    testDuration: '时长',
    footer: '浏览器估算值。',
  },
  ar: {
    title: 'اختبار السرعة',
    subtitle: 'تحليل أداء الشبكة',
    startTest: 'بدء',
    stop: 'إيقاف',
    restartTest: 'إعادة',
    copyResults: 'نسخ',
    copied: 'تم النسخ',
    advertisement: 'إعلان',
    download: 'تحميل',
    upload: 'رفع',
    ping: 'بينغ',
    jitter: 'تذبذب',
    speedOverTime: 'السرعة',
    testingDownload: 'تحميل',
    testingUpload: 'رفع',
    testComplete: 'مكتمل',
    readyToTest: 'جاهز',
    testDuration: 'المدة',
    footer: 'تقدير المتصفح.',
  },
  it: {
    title: 'Test di Velocità',
    subtitle: 'Analisi prestazioni rete',
    startTest: 'Inizia',
    stop: 'Ferma',
    restartTest: 'Riavvia',
    copyResults: 'Copia',
    copied: 'Copiato',
    advertisement: 'Pubblicità',
    download: 'Download',
    upload: 'Upload',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Velocità',
    testingDownload: 'Download',
    testingUpload: 'Upload',
    testComplete: 'Completato',
    readyToTest: 'Pronto',
    testDuration: 'Durata',
    footer: 'Stima del browser.',
  },
  nl: {
    title: 'Snelheidstest',
    subtitle: 'Netwerkprestatie analyse',
    startTest: 'Start',
    stop: 'Stop',
    restartTest: 'Herstarten',
    copyResults: 'Kopiëren',
    copied: 'Gekopieerd',
    advertisement: 'Advertentie',
    download: 'Download',
    upload: 'Upload',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Snelheid',
    testingDownload: 'Download',
    testingUpload: 'Upload',
    testComplete: 'Voltooid',
    readyToTest: 'Gereed',
    testDuration: 'Duur',
    footer: 'Browser schatting.',
  },
  tr: {
    title: 'Hız Testi',
    subtitle: 'Ağ performans analizi',
    startTest: 'Başlat',
    stop: 'Durdur',
    restartTest: 'Yeniden',
    copyResults: 'Kopyala',
    copied: 'Kopyalandı',
    advertisement: 'Reklam',
    download: 'İndirme',
    upload: 'Yükleme',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Hız',
    testingDownload: 'İndirme',
    testingUpload: 'Yükleme',
    testComplete: 'Tamamlandı',
    readyToTest: 'Hazır',
    testDuration: 'Süre',
    footer: 'Tarayıcı tahmini.',
  },
  pl: {
    title: 'Test Prędkości',
    subtitle: 'Analiza wydajności sieci',
    startTest: 'Start',
    stop: 'Stop',
    restartTest: 'Ponów',
    copyResults: 'Kopiuj',
    copied: 'Skopiowano',
    advertisement: 'Reklama',
    download: 'Pobieranie',
    upload: 'Wysyłanie',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Prędkość',
    testingDownload: 'Pobieranie',
    testingUpload: 'Wysyłanie',
    testComplete: 'Ukończono',
    readyToTest: 'Gotowy',
    testDuration: 'Czas',
    footer: 'Oszacowanie przeglądarki.',
  },
  vi: {
    title: 'Kiểm Tra Tốc Độ',
    subtitle: 'Phân tích hiệu suất mạng',
    startTest: 'Bắt đầu',
    stop: 'Dừng',
    restartTest: 'Thử lại',
    copyResults: 'Sao chép',
    copied: 'Đã sao chép',
    advertisement: 'Quảng cáo',
    download: 'Tải xuống',
    upload: 'Tải lên',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Tốc độ',
    testingDownload: 'Tải xuống',
    testingUpload: 'Tải lên',
    testComplete: 'Hoàn thành',
    readyToTest: 'Sẵn sàng',
    testDuration: 'Thời gian',
    footer: 'Ước tính trình duyệt.',
  },
  th: {
    title: 'ทดสอบความเร็ว',
    subtitle: 'วิเคราะห์ประสิทธิภาพเครือข่าย',
    startTest: 'เริ่ม',
    stop: 'หยุด',
    restartTest: 'ทดสอบใหม่',
    copyResults: 'คัดลอก',
    copied: 'คัดลอกแล้ว',
    advertisement: 'โฆษณา',
    download: 'ดาวน์โหลด',
    upload: 'อัพโหลด',
    ping: 'ปิง',
    jitter: 'จิตเตอร์',
    speedOverTime: 'ความเร็ว',
    testingDownload: 'ดาวน์โหลด',
    testingUpload: 'อัพโหลด',
    testComplete: 'เสร็จสิ้น',
    readyToTest: 'พร้อม',
    testDuration: 'เวลา',
    footer: 'ประมาณการเบราว์เซอร์',
  },
  id: {
    title: 'Tes Kecepatan',
    subtitle: 'Analisis kinerja jaringan',
    startTest: 'Mulai',
    stop: 'Berhenti',
    restartTest: 'Ulangi',
    copyResults: 'Salin',
    copied: 'Disalin',
    advertisement: 'Iklan',
    download: 'Unduh',
    upload: 'Unggah',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Kecepatan',
    testingDownload: 'Unduh',
    testingUpload: 'Unggah',
    testComplete: 'Selesai',
    readyToTest: 'Siap',
    testDuration: 'Durasi',
    footer: 'Estimasi browser.',
  },
  ms: {
    title: 'Ujian Kelajuan',
    subtitle: 'Analisis prestasi rangkaian',
    startTest: 'Mula',
    stop: 'Berhenti',
    restartTest: 'Ulang',
    copyResults: 'Salin',
    copied: 'Disalin',
    advertisement: 'Iklan',
    download: 'Muat turun',
    upload: 'Muat naik',
    ping: 'Ping',
    jitter: 'Jitter',
    speedOverTime: 'Kelajuan',
    testingDownload: 'Muat turun',
    testingUpload: 'Muat naik',
    testComplete: 'Selesai',
    readyToTest: 'Sedia',
    testDuration: 'Tempoh',
    footer: 'Anggaran pelayar.',
  },
  hi: {
    title: 'इंटरनेट स्पीड टेस्ट',
    subtitle: 'नेटवर्क प्रदर्शन विश्लेषण',
    startTest: 'टेस्ट शुरू करें',
    stop: 'रोकें',
    restartTest: 'पुनः प्रारंभ',
    copyResults: 'कॉपी करें',
    copied: 'कॉपी हो गया',
    advertisement: 'विज्ञापन',
    download: 'डाउनलोड',
    upload: 'अपलोड',
    ping: 'पिंग',
    jitter: 'जिटर',
    speedOverTime: 'गति',
    testingDownload: 'डाउनलोड टेस्ट',
    testingUpload: 'अपलोड टेस्ट',
    testComplete: 'पूरा हुआ',
    readyToTest: 'तैयार',
    testDuration: 'अवधि',
    footer: 'ब्राउज़र अनुमान।',
  },
  bn: {
    title: 'স্পিড টেস্ট',
    subtitle: 'নেটওয়ার্ক পারফরম্যান্স বিশ্লেষণ',
    startTest: 'শুরু করুন',
    stop: 'থামান',
    restartTest: 'আবার',
    copyResults: 'কপি',
    copied: 'কপি হয়েছে',
    advertisement: 'বিজ্ঞাপন',
    download: 'ডাউনলোড',
    upload: 'আপলোড',
    ping: 'পিং',
    jitter: 'জিটার',
    speedOverTime: 'গতি',
    testingDownload: 'ডাউনলোড',
    testingUpload: 'আপলোড',
    testComplete: 'সম্পন্ন',
    readyToTest: 'প্রস্তুত',
    testDuration: 'সময়',
    footer: 'ব্রাউজার অনুমান।',
  },
  te: {
    title: 'స్పీడ్ టెస్ట్',
    subtitle: 'నెట్‌వర్క్ పనితీరు విశ్లేషణ',
    startTest: 'ప్రారంభించు',
    stop: 'ఆపు',
    restartTest: 'మళ్ళీ',
    copyResults: 'కాపీ',
    copied: 'కాపీ అయింది',
    advertisement: 'ప్రకటన',
    download: 'డౌన్‌లోడ్',
    upload: 'అప్‌లోడ్',
    ping: 'పింగ్',
    jitter: 'జిట్టర్',
    speedOverTime: 'వేగం',
    testingDownload: 'డౌన్‌లోడ్',
    testingUpload: 'అప్‌లోడ్',
    testComplete: 'పూర్తయింది',
    readyToTest: 'సిద్ధం',
    testDuration: 'సమయం',
    footer: 'బ్రౌజర్ అంచనా.',
  },
  mr: {
    title: 'स्पीड टेस्ट',
    subtitle: 'नेटवर्क कामगिरी विश्लेषण',
    startTest: 'सुरू करा',
    stop: 'थांबा',
    restartTest: 'पुन्हा',
    copyResults: 'कॉपी',
    copied: 'कॉपी झाले',
    advertisement: 'जाहिरात',
    download: 'डाउनलोड',
    upload: 'अपलोड',
    ping: 'पिंग',
    jitter: 'जिटर',
    speedOverTime: 'वेग',
    testingDownload: 'डाउनलोड',
    testingUpload: 'अपलोड',
    testComplete: 'पूर्ण',
    readyToTest: 'तयार',
    testDuration: 'कालावधी',
    footer: 'ब्राउझर अंदाज.',
  },
  ta: {
    title: 'வேக சோதனை',
    subtitle: 'நெட்வொர்க் செயல்திறன் பகுப்பாய்வு',
    startTest: 'தொடங்கு',
    stop: 'நிறுத்து',
    restartTest: 'மீண்டும்',
    copyResults: 'நகல்',
    copied: 'நகலெடுக்கப்பட்டது',
    advertisement: 'விளம்பரம்',
    download: 'பதிவிறக்கம்',
    upload: 'பதிவேற்றம்',
    ping: 'பிங்',
    jitter: 'ஜிட்டர்',
    speedOverTime: 'வேகம்',
    testingDownload: 'பதிவிறக்கம்',
    testingUpload: 'பதிவேற்றம்',
    testComplete: 'முடிந்தது',
    readyToTest: 'தயார்',
    testDuration: 'நேரம்',
    footer: 'உலாவி மதிப்பீடு.',
  },
  gu: {
    title: 'સ્પીડ ટેસ્ટ',
    subtitle: 'નેટવર્ક પ્રદર્શન વિશ્લેષણ',
    startTest: 'શરૂ કરો',
    stop: 'રોકો',
    restartTest: 'ફરીથી',
    copyResults: 'કૉપી',
    copied: 'કૉપી થયું',
    advertisement: 'જાહેરાત',
    download: 'ડાઉનલોડ',
    upload: 'અપલોડ',
    ping: 'પિંગ',
    jitter: 'જીટર',
    speedOverTime: 'ઝડપ',
    testingDownload: 'ડાઉનલોડ',
    testingUpload: 'અપલોડ',
    testComplete: 'પૂર્ણ',
    readyToTest: 'તૈયાર',
    testDuration: 'સમય',
    footer: 'બ્રાઉઝર અંદાજ.',
  },
  kn: {
    title: 'ಸ್ಪೀಡ್ ಟೆಸ್ಟ್',
    subtitle: 'ನೆಟ್‌ವರ್ಕ್ ಕಾರ್ಯಕ್ಷಮತೆ ವಿಶ್ಲೇಷಣೆ',
    startTest: 'ಪ್ರಾರಂಭಿಸಿ',
    stop: 'ನಿಲ್ಲಿಸಿ',
    restartTest: 'ಮತ್ತೆ',
    copyResults: 'ನಕಲು',
    copied: 'ನಕಲಾಗಿದೆ',
    advertisement: 'ಜಾಹೀರಾತು',
    download: 'ಡೌನ್‌ಲೋಡ್',
    upload: 'ಅಪ್‌ಲೋಡ್',
    ping: 'ಪಿಂಗ್',
    jitter: 'ಜಿಟ್ಟರ್',
    speedOverTime: 'ವೇಗ',
    testingDownload: 'ಡೌನ್‌ಲೋಡ್',
    testingUpload: 'ಅಪ್‌ಲೋಡ್',
    testComplete: 'ಪೂರ್ಣ',
    readyToTest: 'ಸಿದ್ಧ',
    testDuration: 'ಸಮಯ',
    footer: 'ಬ್ರೌಸರ್ ಅಂದಾಜು.',
  },
  ml: {
    title: 'സ്പീഡ് ടെസ്റ്റ്',
    subtitle: 'നെറ്റ്‌വർക്ക് പ്രകടന വിശകലനം',
    startTest: 'ആരംഭിക്കുക',
    stop: 'നിർത്തുക',
    restartTest: 'വീണ്ടും',
    copyResults: 'പകർത്തുക',
    copied: 'പകർത്തി',
    advertisement: 'പരസ്യം',
    download: 'ഡൗൺലോഡ്',
    upload: 'അപ്‌ലോഡ്',
    ping: 'പിംഗ്',
    jitter: 'ജിറ്റർ',
    speedOverTime: 'വേഗത',
    testingDownload: 'ഡൗൺലോഡ്',
    testingUpload: 'അപ്‌ലോഡ്',
    testComplete: 'പൂർത്തിയായി',
    readyToTest: 'തയ്യാർ',
    testDuration: 'സമയം',
    footer: 'ബ്രൗസർ കണക്ക്.',
  },
  or: {
    title: 'ସ୍ପିଡ୍ ଟେଷ୍ଟ୍',
    subtitle: 'ନେଟୱାର୍କ ପ୍ରଦର୍ଶନ ବିଶ୍ଲେଷଣ',
    startTest: 'ଆରମ୍ଭ କରନ୍ତୁ',
    stop: 'ବନ୍ଦ କରନ୍ତୁ',
    restartTest: 'ପୁଣି',
    copyResults: 'କପି',
    copied: 'କପି ହେଲା',
    advertisement: 'ବିଜ୍ଞାପନ',
    download: 'ଡାଉନଲୋଡ୍',
    upload: 'ଅପଲୋଡ୍',
    ping: 'ପିଙ୍ଗ',
    jitter: 'ଜିଟର',
    speedOverTime: 'ବେଗ',
    testingDownload: 'ଡାଉନଲୋଡ୍',
    testingUpload: 'ଅପଲୋଡ୍',
    testComplete: 'ସମ୍ପୂର୍ଣ୍ଣ',
    readyToTest: 'ପ୍ରସ୍ତୁତ',
    testDuration: 'ସମୟ',
    footer: 'ବ୍ରାଉଜର ଅନୁମାନ।',
  },
  pa: {
    title: 'ਸਪੀਡ ਟੈਸਟ',
    subtitle: 'ਨੈੱਟਵਰਕ ਪ੍ਰਦਰਸ਼ਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    startTest: 'ਸ਼ੁਰੂ ਕਰੋ',
    stop: 'ਰੋਕੋ',
    restartTest: 'ਦੁਬਾਰਾ',
    copyResults: 'ਕਾਪੀ',
    copied: 'ਕਾਪੀ ਹੋਇਆ',
    advertisement: 'ਇਸ਼ਤਿਹਾਰ',
    download: 'ਡਾਊਨਲੋਡ',
    upload: 'ਅੱਪਲੋਡ',
    ping: 'ਪਿੰਗ',
    jitter: 'ਜਿਟਰ',
    speedOverTime: 'ਸਪੀਡ',
    testingDownload: 'ਡਾਊਨਲੋਡ',
    testingUpload: 'ਅੱਪਲੋਡ',
    testComplete: 'ਪੂਰਾ',
    readyToTest: 'ਤਿਆਰ',
    testDuration: 'ਸਮਾਂ',
    footer: 'ਬ੍ਰਾਊਜ਼ਰ ਅੰਦਾਜ਼ਾ।',
  },
  as: {
    title: 'স্পীড টেষ্ট',
    subtitle: 'নেটৱৰ্ক পাৰফৰমেন্স বিশ্লেষণ',
    startTest: 'আৰম্ভ কৰক',
    stop: 'বন্ধ কৰক',
    restartTest: 'পুনৰ',
    copyResults: 'কপি',
    copied: 'কপি হৈছে',
    advertisement: 'বিজ্ঞাপন',
    download: 'ডাউনলোড',
    upload: 'আপলোড',
    ping: 'পিং',
    jitter: 'জিটাৰ',
    speedOverTime: 'গতি',
    testingDownload: 'ডাউনলোড',
    testingUpload: 'আপলোড',
    testComplete: 'সম্পূৰ্ণ',
    readyToTest: 'সাজু',
    testDuration: 'সময়',
    footer: 'ব্ৰাউজাৰ অনুমান।',
  },
  ur: {
    title: 'سپیڈ ٹیسٹ',
    subtitle: 'نیٹ ورک کارکردگی تجزیہ',
    startTest: 'شروع کریں',
    stop: 'روکیں',
    restartTest: 'دوبارہ',
    copyResults: 'کاپی',
    copied: 'کاپی ہوگیا',
    advertisement: 'اشتہار',
    download: 'ڈاؤن لوڈ',
    upload: 'اپ لوڈ',
    ping: 'پنگ',
    jitter: 'جٹر',
    speedOverTime: 'رفتار',
    testingDownload: 'ڈاؤن لوڈ',
    testingUpload: 'اپ لوڈ',
    testComplete: 'مکمل',
    readyToTest: 'تیار',
    testDuration: 'وقت',
    footer: 'براؤزر تخمینہ۔',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
